name: github action push package to registry
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ['1.21.x']
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
            go-version: ${{ matrix.go-version }}
      - name: package api init go module
        run: cd api && go mod tidy
      - name: check docker version
        run: cd .. && docker version
      
        
    
